/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../objects/gameobject.ts" />
/// <reference path="../objects/player.ts" />
/// <reference path="../objects/road.ts" />
/// <reference path="../objects/gas.ts"/>
/// <reference path="../objects/car.ts"/>
/// <reference path="../objects/car2.ts"/>
/// <reference path="../objects/car3.ts"/>
/// <reference path="../objects/car4.ts"/>
/// <reference path="../objects/water.ts"/>
/// <reference path="../objects/camel.ts"/>
/// <reference path="../objects/cactus.ts"/>
/// <reference path="../objects/desert.ts"/>
/// <reference path="../managers/collision.ts" />
/// <reference path="../managers/collision2.ts" />
/// <reference path="../managers/collision3.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/instruction1.ts" />
/// <reference path="../scenes/instruction2.ts" />
/// <reference path="../scenes/instruction3.ts" />
/// <reference path="../scenes/level1.ts" />
/// <reference path="../scenes/level2.ts" />
/// <reference path="../scenes/level3.ts" />
/// <reference path="../scenes/end.ts" />
/// <reference path="../scenes/win.ts" /> 
//# sourceMappingURL=_reference.js.map